/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
  public static void main(String[] args) {
    Manager manager = new Manager();

    manager.setLogin("thales");
    manager.setPassword("123456");
    manager.setName("Thales Nishida");

    System.out.println(manager.getName());
    System.out.println(manager.getLogin());
    System.out.println(manager.getPassword());
  }
}
